version: "3.8"

services:

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=anchtun
      - GF_SECURITY_ADMIN_PASSWORD=password123
    networks:
     - anchtun-network
    depends_on:
      - prometheus 
      
  prometheus:
   image: prom/prometheus:latest
   ports:
      - "9090:9090"
   volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
   networks:
    - anchtun-network
    
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
     - anchtun-network
     
  configserver:
    image: anchtun/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - anchtun-network
    depends_on:
     - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
     
  eurekaserver:
    image: anchtun/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - anchtun-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
# Env. Variables
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
       
  account:
    image: anchtun/account:latest
    mem_limit: 700m
    ports:
      - "8010:8010"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      
#  account2:
#    image: anchtun/account:latest
#    mem_limit: 700m
#    ports:
#      - "8011:8010"
#    networks:
#      - anchtun-network
#    depends_on:
#      - configserver
#      - eurekaserver
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 30s
#        max_attempts: 3
#        window: 120s
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
#      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    
  loan:
    image: anchtun/loan:latest
    mem_limit: 700m
    ports:
      - "8030:8030"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    
  card:
    image: anchtun/card:latest
    mem_limit: 700m
    ports:
      - "8020:8020"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  gatewayserver:
    image: anchtun/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
      - account
      - loan
      - card
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    
networks:
  anchtun-network:
  
  