global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'account'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['account:8010']
  - job_name: 'loan'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['loan:8030']
  - job_name: 'card'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['card:8020']