version: "3.8"

services:

  account:
    image: anchtun/account:latest
    mem_limit: 700m
    ports:
      - "8010:8010"
      - "8011:8010"
    networks:
      - anchtun-network
    
  loan:
    image: anchtun/loan:latest
    mem_limit: 700m
    ports:
      - "8030:8030"
    networks:
      - anchtun-network
    
  card:
    image: anchtun/card:latest
    mem_limit: 700m
    ports:
      - "8020:8020"
    networks:
      - anchtun-network
    
networks:
  anchtun-network: