# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: account-deployment
deploymentLabel: account

replicaCount: 1

image:
  repository: anchtun1212/account
  tag: latest

containerPort: 8010

service:
  type: LoadBalancer
  port: 8010
  targetPort: 8010

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true