# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: card-deployment
deploymentLabel: card

replicaCount: 1

image:
  repository: anchtun1212/card
  tag: latest

containerPort: 8020

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
