version: "3.8"

services:

  configserver:
    image: anchtun/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - anchtun-network
     
  eurekaserver:
    image: anchtun/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - anchtun-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
# Env. Variables
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/ 
       
  account:
    image: anchtun/account:latest
    mem_limit: 700m
    ports:
      - "8010:8010"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
  account2:
    image: anchtun/account:latest
    mem_limit: 700m
    ports:
      - "8011:8010"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  loan:
    image: anchtun/loan:latest
    mem_limit: 700m
    ports:
      - "8030:8030"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  card:
    image: anchtun/card:latest
    mem_limit: 700m
    ports:
      - "8020:8020"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  gatewayserver:
    image: anchtun/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - anchtun-network
    depends_on:
      - configserver
      - eurekaserver
      - account
      - loan
      - card
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
networks:
  anchtun-network: